name: flutter_screen_shot_writer
description: network server to create screenshots
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  test_process: ^2.0.2
